import Experience from "@/entities/experience";

export const experiences: Experience[] = [
  new Experience({
    nameEn: "IT Student Group Tech.Uni",
    roleEn: "Deputy Representative",
    nameJa: "IT 系学生団体 Tech.Uni",
    roleJa: "副代表",
    start: new Date("2022-10"),
    end: new Date("2023-08"),
  }),
  new Experience({
    nameEn: "Re-era, inc.",
    roleEn: "Full-stack Engineer (Internship)",
    nameJa: "株式会社 Re-era",
    roleJa: "フルスタックエンジニア (インターン)",
    start: new Date("2023-08"),
    end: new Date("2024-05"),
  }),
  new Experience({
    nameEn: "IT Student Group Tech.Uni",
    roleEn: "Representative",
    nameJa: "IT 系学生団体 Tech.Uni",
    roleJa: "代表",
    start: new Date("2023-09"),
    end: new Date("2024-10"),
  }),
  new Experience({
    nameEn: "CyberAgent, inc.",
    roleEn: "iOS Engineer (Internship)",
    nameJa: "株式会社 サイバーエージェント",
    roleJa: "iOS エンジニア (インターン)",
    start: new Date("2024-02"),
    end: new Date("2024-03"),
  }),
  new Experience({
    nameEn: "Atmark Solutions, inc.",
    roleEn: "iOS / Android Engineer (Internship)",
    nameJa: "アットマークソリューション 株式会社",
    roleJa: "iOS / Android エンジニア (インターン)",
    start: new Date("2024-06"),
  }),
  new Experience({
    nameEn: "Cybozu, inc.",
    roleEn: "iOS Engineer (Internship)",
    nameJa: "サイボウズ 株式会社",
    roleJa: "iOS エンジニア (インターン)",
    start: new Date("2024-09"),
    end: new Date("2024-09"),
  }),
  new Experience({
    nameEn: "STORES, inc.",
    roleEn: "iOS Engineer (Internship)",
    nameJa: "STORES 株式会社",
    roleJa: "iOS エンジニア (インターン)",
    start: new Date("2024-09"),
    end: new Date("2024-10"),
  }),
  new Experience({
    nameEn: "STORES, inc.",
    roleEn: "iOS Engineer (Part-time)",
    nameJa: "STORES 株式会社",
    roleJa: "iOS エンジニア (アルバイト)",
    start: new Date("2025-02"),
  }),
];